application:
  author: Mayllon Baumer

spring:
  h2:
    console.enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true